### ISSUE TITLE
App crashing on IOS 13

### ISSUE THREAD

**Issue by patriksharma** [handsomecode/InteractiveSideMenu#114] opened 2019-10-14 12:38 UTC
App crashing as soon as I click on Side menu button

```
 *** Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/UIApplication.m:5240
2019-10-14 18:05:26.260454+0530 POA[6475:1240923] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'
```

**Comment by numanayhan** [comment] 2019-10-15 12:46
Duplicate of Me to app Crashing

**Comment by patriksharma** [comment] 2019-10-15 12:47
@numanayhan  I have done a temporary fix. Comment statusbar is hidden and status bar line in repo

**Comment by patriksharma** [comment] 2019-10-15 13:52
```
//let statusBar: UIView = UIApplication.shared.value(forKey: "statusBar") as! UIView
        //statusBar.isHidden = true
```

**Comment by jbarros35** [comment] 2019-10-29 11:44
its all broken. you cannot rift without a fork.

**Closed** 2020-01-02 21:15 UTC
